name: Test

on:
  workflow_dispatch:
    inputs:
      csv:
        description: "CSV file"
        required: true

jobs:
  generate:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test 1
        env:
          csv: ${{ github.event.inputs.csv }}
        run: |
          echo "$csv"
